AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  covid19-data-viewer-function

  Sample SAM Template for covid19-data-viewer-function

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 5

Resources:
  COVID19DataViewerAPI:
    Type: AWS::Serverless::Api
    Properties:
      Name: COVID19DataViewerAPI
      StageName: test
      TracingEnabled: true
      EndpointConfiguration: REGIONAL
      OpenApiVersion: 3.0.1
      Tags:
        NameTag: EventPublisher API
        ConsumerAppTag: Thirdparty
      Auth:
        ApiKeyRequired: true  
  COVID19DataViewerFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      FunctionName: covid19-data-viewer-function
      Description: covid19-data-viewer-function
      CodeUri: lambda_code/
      Handler: app.lambda_handler
      Runtime: python3.7
      Layers:
        - !Join
          - ''
          - - 'arn:aws:lambda:'
            - !Ref 'AWS::Region'
            - ':'
            - !Ref 'AWS::AccountId'
            - ':layer:request-layer-python:1'
        - !Join
          - ''
          - - 'arn:aws:lambda:'
            - !Ref 'AWS::Region'
            - ':'
            - !Ref 'AWS::AccountId'
            - ':layer:xray-layer-python:1'
      MemorySize: 512
      Timeout: 5
      AutoPublishAlias: live
      Tracing: Active
      ReservedConcurrentExecutions: 10
      Environment:
        Variables:
          AWS_XRAY_TRACING_NAME: covid19-data-viewer-function
          COVD19_DYNAMO_TABLE: covid19-stats
      Policies:
        - AWSLambdaExecute
        - Version: '2012-10-17'
          Statement:
            - Effect: Allow
              Action:
                  - dynamodb:DescribeTable
                  - dynamodb:GetItem
                  - dynamodb:DeleteItem
                  - dynamodb:PutItem
                  - dynamodb:UpdateItem
                  - dynamodb:BatchWriteItem
                  - dynamodb:BatchGetItem
                  - dynamodb:Query
                  - dynamodb:Scan
                  - dynamodb:ConditionCheckItem
              Resource: !Join
                  - ''
                  - - 'arn:aws:dynamodb:'
                    - !Ref 'AWS::Region'
                    - ':'
                    - !Ref 'AWS::AccountId'
                    - ':table/covid19-stats'
      Events:
        COVID19DataViewerAPIEvent:
          Type: Api
          Properties:
            Path: /covid19/countries/{country}/latest
            Method: get
            RestApiId:
              Ref: COVID19DataViewerAPI                      
      Tags: 
        NameTag: covid19-data-viewer-function
        ConsumerAppTag: API Gateway

  COVID19DataViewerAPIKey:
    Type: AWS::ApiGateway::ApiKey
    Properties:
      Name:
        Fn::Join:
        - ''
        - - Ref: AWS::StackName
          - -apikey
      Description: CloudFormation API Key V1
      Enabled: true
      GenerateDistinctId: false
  COVID19DataViewerAPIUsagePlan:
    Type: AWS::ApiGateway::UsagePlan
    Properties:
      ApiStages:
      - ApiId:
          Ref: COVID19DataViewerAPI
        Stage: test
      Description:
        Fn::Join:
        - ' '
        - - Ref: AWS::StackName
          - usage plan
      Quota:
        Limit: 2000
        Period: MONTH
      Throttle:
        BurstLimit: 10
        RateLimit: 10
      UsagePlanName:
        Fn::Join:
        - ''
        - - Ref: AWS::StackName
          - -usage-plan
    DependsOn:
    - COVID19DataViewerAPI
    - StageTestCOVID19DataViewerAPI
  StageTestCOVID19DataViewerAPI:
    Type: AWS::ApiGateway::Stage
    Properties:
      DeploymentId:
        Ref: DeploymentCOVID19DataViewerAPI
      RestApiId:
        Ref: COVID19DataViewerAPI
      StageName: test1
      MethodSettings:
      - HttpMethod: '*'
        ResourcePath: /*
        DataTraceEnabled: true
        LoggingLevel: INFO
        MetricsEnabled: true
        ThrottlingBurstLimit: 2000
        ThrottlingRateLimit: 2000
  DeploymentCOVID19DataViewerAPI:
    Type: AWS::ApiGateway::Deployment
    Properties:
      RestApiId:
        Ref: COVID19DataViewerAPI
  COVID19DataViewerAPIUsagePlanKey:
    Type: AWS::ApiGateway::UsagePlanKey
    Properties:
      KeyId:
        Ref: COVID19DataViewerAPIKey
      KeyType: API_KEY
      UsagePlanId:
        Ref: COVID19DataViewerAPIUsagePlan
    DependsOn:
    - COVID19DataViewerAPIUsagePlan
    - COVID19DataViewerAPIKey
Outputs:
  # ServerlessRestApi is an implicit API created out of Events key under Serverless::Function
  # Find out more about other implicit resources you can reference within SAM
  # https://github.com/awslabs/serverless-application-model/blob/master/docs/internals/generated_resources.rst#api
  COVID19DataViewerAPI:
    Description: API Gateway endpoint URL for test stage
    Value:
      Fn::Sub: https://${COVID19DataViewerAPI}.execute-api.${AWS::Region}.amazonaws.com/test/covid19/countries/{conutry}/latest
  COVID19DataViewerFunction:
    Description: "covid19-data-viewer-function ARN"
    Value: !GetAtt COVID19DataViewerFunction.Arn
  COVID19DataViewerFunctionIamRole:
    Description: "Implicit IAM Role created for covid19-data-viewer-function"
    Value: !GetAtt COVID19DataViewerFunctionRole.Arn
